server:
  port: 8888
spring:
  resources:
    static-locations: classpath:/statics/,classpath:/templates/
  redis:
    host: localhost
    port: 6379
#添加Thymeleaf配置
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
