version: "3.5"
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/data/mysql:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    network_mode: host
  redis:
    image: redis:latest
    restart: always
    hostname: redis
    container_name: redis
    # 使用该参数，container内的root拥有真正的root权限。否则，container内的root只是外部的一个普通用户权限。privileged启动的容器，可以看到很多host上的设备，并且可以执行mount。甚至允许你在docker容器中启动docker容器。
    privileged: true
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./redis/data/redis/:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data/redis/logs:/logs
    command: ["redis-server","/etc/redis/redis.conf"]
    network_mode: host