server:
  port: 9091
spring:
  elasticsearch:
    rest:
      uris: http://my.service.com:9200
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
